apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xbelake-ambulance-ufe-content
spec:
  microFrontend: xbelake-ambulance-ufe
  element: xbelake-ambulance-wl-list
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xbelake-ambulance-wl(/.*)?$"