apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xbelake-ambulance-ufe-content
spec:
  microFrontend: xbelake-ambulance-ufe
  element: xbelake-ambulance-wl-app
  attributes:
    - name: api-base
      value: http://localhost:5001/api
    - name: ambulance-id
      value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xbelake-ambulance-wl(/.*)?$"