apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
  namespace: default
spec:
  acme:
    email: <your-email>  # TODO: set email
    server: https://acme-staging-v02.api.letsencrypt.org/directory  # Use this for testing | Production: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: wac-hospital-gateway
                namespace: wac-hospital
                kind: Gateway
